name: Test

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure temporary git user
        run: |
          git config user.name "grit"
          git config user.email "grit@example.org"
      - name: Run test script
        run: ./script.sh test